#!/bin/sh
echo "Set Nomad Server"
export nomad_server="<Enter_nomad_server_address>"
echo "Set Env"
export env="<Enter_Environment>"
echo "Set region"
export region="<Enter_Region_of_your_service>"
echo "Set pdservicekey"
export pdservicekey="<Enter_pager_duty_service_integration_key>"
echo "Set alert switch"
export alert_switch="<Enter_on_or_off>"
echo "Set consul_server"
export consul_server="<Enter_Consul_Server_Address>"
echo "Set consul datacenter"
export consul_datacenter="<Enter_Consul_Datacenter>"
