#!/bin/sh
echo "Set Nomad Server"
export nomad_server="<Enter_nomad_server_address>"
echo "Set Env"
export env="<Enter_Environment>"
echo "Set region"
export region="<Enter_Region_of_your_service>"
echo "Set pdservicekey"
export consul_server="<Enter_Consul_Server_Address>"
echo "Set consul datacenter"
export consul_datacenter="<Enter_Consul_Datacenter>"
